import {DEFAULTS,SOURCES,analyze,settings,validateObservations} from './core.js';
import {sourceStatus,scanRemote} from './providers.js';
import {demoData} from './demo.js';
import {lookupOpenLibrary} from './metadata.js';
const $=s=>document.querySelector(s), key='book-scanner-v1';
let rows=[], prefs=settings(), demo=false, latest=[];
const euro=v=>v===null?'—':new Intl.NumberFormat('el-GR',{style:'currency',currency:'EUR'}).format(v);
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function message(text,error=false){$('#message').textContent=text;$('#message').className=error?'error':'';}
function save(){if(demo)return;try{localStorage.setItem(key,JSON.stringify({observations:rows,settings:prefs}));}catch{message('Δεν ήταν δυνατή η αποθήκευση. Κάνε εξαγωγή JSON.',true);}}
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved){rows=validateObservations(saved.observations);prefs=settings(saved.settings);}}catch{message('Τα αποθηκευμένα δεδομένα δεν φορτώθηκαν. Μπορείς να κάνεις νέα εισαγωγή.',true);}
const labels={buyProfit:'BUY κέρδος ≥ €',buyROI:'BUY ROI ≥ %',watchMin:'WATCH από €',watchMax:'WATCH έως €',minConfidence:'Βεβαιότητα ≥ %',maxPurchase:'Αγορά έως €',maxCompetition:'Ανταγωνισμός έως',minDemand:'Ζήτηση ≥ άτομα',minScarcity:'Σπανιότητα ≥ %',maxTurnover:'Πώληση έως ημέρες',maxAgeHours:'Τιμές έως ώρες',feePercent:'Προμήθεια %',feeFixed:'Σταθερή χρέωση €',shippingIn:'Μεταφορικά αγοράς €',shippingOut:'Μεταφορικά πώλησης €',packaging:'Συσκευασία €',resaleDiscount:'Έκπτωση εκτίμησης %'};
for(const [name,label] of Object.entries(labels)){const l=node('label',label),i=node('input');Object.assign(i,{name,type:'number',min:'0',step:'0.01',required:true});if(['feePercent','minConfidence','minScarcity'].includes(name))i.max='100';if(name==='resaleDiscount')i.max='99';l.append(i);$('#thresholds').append(l);}
for(const source of SOURCES){const l=node('label',undefined,'check'),i=node('input');Object.assign(i,{type:'checkbox',name:'source',value:source.id});l.append(i,document.createTextNode(source.name));$('#sources').append(l);const o=node('option',source.name);o.value=source.id;$('#entry-source').append(o);}
function fillSettings(){for(const k of Object.keys(labels))$('#filters').elements[k].value=prefs[k];$('#filters').elements.exactOnly.checked=prefs.exactOnly;document.querySelectorAll('[name=source][type=checkbox]').forEach(i=>i.checked=prefs.sources.includes(i.value));}
function readSettings(){const form=$('#filters');return settings({...Object.fromEntries(Object.keys(labels).map(k=>[k,Number(form.elements[k].value)])),exactOnly:form.elements.exactOnly.checked,sources:[...document.querySelectorAll('[name=source]:checked')].map(i=>i.value)});}
function render(){
  latest=analyze(rows,prefs,$('#query').value);$('#record-count').textContent=`${rows.length} εγγραφές · ${latest.length} αγορές`;
  for(const c of ['BUY','WATCH','PASS'])$('#'+c.toLowerCase()+'-count').textContent=latest.filter(x=>x.classification===c).length;
  $('#mode').textContent=demo?'ΣΥΝΘΕΤΙΚΟ ΔΕΙΓΜΑ · Δεν είναι πραγματικές αγγελίες. Δεν αποθηκεύεται ούτε παράγει ειδοποιήσεις.':'Χειροκίνητα / εισαγόμενα δεδομένα · Η ηλικία κάθε τιμής ελέγχεται στην ανάλυση.';
  $('#mode').classList.toggle('demo',demo);
  $('#clear').textContent=demo?'Κλείσιμο δείγματος':'Διαγραφή λίστας';
  $('#observations').replaceChildren();
  for(const r of rows){const line=node('div',undefined,'observation-row');line.append(node('span',`${r.title} · ${r.kind} · ${euro(r.price)} · ${new Date(r.observedAt).toLocaleString('el-GR')}`));const remove=node('button','Αφαίρεση','secondary');remove.type='button';remove.onclick=()=>{rows=rows.filter(x=>x.id!==r.id);save();render();};line.append(remove);$('#observations').append(line);}
  $('#results').replaceChildren();const visible=latest.filter(r=>$('#classification').value==='all'||r.classification===$('#classification').value);
  if(!visible.length){const e=node('div',undefined,'empty');e.append(node('strong',rows.length?'Δεν υπάρχουν αποτελέσματα για αυτά τα φίλτρα.':'Η πρώτη σου ευκαιρία αρχίζει εδώ.'),node('p','Πρόσθεσε μια διαθέσιμη αγγελία και συγκριτικές τιμές της ίδιας έκδοσης ή δοκίμασε το συνθετικό δείγμα.'));$('#results').append(e);}
  for(const r of visible){
    const card=node('article',undefined,'card'),top=node('div',undefined,'card-top'),title=node('div');
    title.append(node('small',`${SOURCES.find(s=>s.id===r.buy.source).name} · ${r.buy.isbn||'Χωρίς ISBN'}`),node('h3',r.buy.title),node('small',[r.buy.author,r.buy.publisher].filter(Boolean).join(' · ')));top.append(title,node('span',r.classification,'badge '+r.classification));card.append(top);
    const metrics=node('div',undefined,'metrics');for(const [label,value] of [['Αγορά',euro(r.buy.price)],['Εκτίμηση πώλησης',euro(r.resale)],['Καθαρό κέρδος',euro(r.profit)],['ROI',r.roi===null?'—':r.roi+'%']]){const m=node('div');m.append(node('span',label),node('b',value));metrics.append(m);}card.append(metrics);
    card.append(node('p',`Βεβαιότητα ${r.confidence}% · ${r.matchType} · Ελέγχθηκε ${new Date(r.buy.observedAt).toLocaleString('el-GR')}`));
    const a=node('a','Άνοιγμα καταχώρισης ↗');a.href=r.buy.url;a.target='_blank';a.rel='noopener noreferrer';card.append(a);
    const details=node('details');details.append(node('summary','Υπολογισμός & στοιχεία σύγκρισης'));
    details.append(node('p',`Συνολική αγορά ${euro(r.cost)} · Προμήθειες ${euro(r.fees)} · Έξοδα πώλησης / συσκευασίας ${euro(r.expenses)}. ROI = κέρδος / (τιμή αγοράς + μεταφορικά αγοράς).`),node('p',`Ανταγωνισμός: ${r.competition??'άγνωστος'} · Ενδιαφερόμενοι: ${r.demand??'άγνωστοι'} · Σπανιότητα: ${r.scarcity===null?'άγνωστη':r.scarcity+'%'} · Εκτιμώμενη πώληση: ${r.turnoverDays??'άγνωστο'} ημέρες. Συγκριτικές ενεργές αγγελίες στο δείγμα: ${r.observedCompetition}.`));
    const reasons=node('ul');r.reasons.forEach(x=>reasons.append(node('li',x)));details.append(reasons);
    const comps=node('ul');for(const c of r.comparables){const li=node('li'),link=node('a',`${c.source} · ${c.kind} · ${euro(c.price)} · ${c.condition} · ${new Date(c.observedAt).toLocaleString('el-GR')}`);link.href=c.url;link.target='_blank';link.rel='noopener noreferrer';li.append(link);comps.append(li);}details.append(comps);
    const remove=node('button','Αφαίρεση αγγελίας','secondary delete');remove.addEventListener('click',()=>{rows=rows.filter(x=>x.id!==r.buy.id);save();render();});details.append(remove);card.append(details);$('#results').append(card);
  }
}
fillSettings();
if(matchMedia('(max-width: 620px)').matches)$('aside details').open=false;
function setDate(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('#observation').elements.observedAt.value=d.toISOString().slice(0,16);}setDate();
$('#isbn-lookup').onclick=async()=>{const button=$('#isbn-lookup'),form=$('#observation'),status=$('#metadata-status');button.disabled=true;status.textContent='Αναζήτηση έκδοσης…';try{const book=await lookupOpenLibrary(form.elements.isbn.value);form.elements.isbn.value=book.isbn;form.elements.title.value=book.title;form.elements.author.value=book.author;form.elements.publisher.value=book.publisher;status.replaceChildren(document.createTextNode(`Συμπληρώθηκε από ${book.source}${book.cached?' (τοπικά αποθηκευμένο)':''} · `));const link=node('a','Έλεγχος εγγραφής ↗');link.href=book.sourceUrl;link.target='_blank';link.rel='noopener noreferrer';status.append(link);}catch(err){status.textContent=err.message;}finally{button.disabled=false;}};
$('#filters').addEventListener('submit',e=>{e.preventDefault();try{prefs=readSettings();save();render();message('Τα φίλτρα εφαρμόστηκαν.');}catch(err){message(err.message,true);}});
$('#reset').onclick=()=>{prefs=settings();fillSettings();save();render();};
$('#search').onsubmit=e=>{e.preventDefault();try{prefs=readSettings();render();save();message(`Αναλύθηκαν ${latest.length} πιθανές αγορές.`);}catch(err){message(err.message,true);}};
$('#classification').onchange=render;
$('#observation').onsubmit=e=>{e.preventDefault();try{if(demo)throw Error('Διάγραψε πρώτα το συνθετικό δείγμα για να καταχωρίσεις πραγματικά δεδομένα.');const data=Object.fromEntries(new FormData(e.target));for(const k of ['price','demand','competition','turnoverDays','shippingIn']) data[k]=data[k]===''?null:Number(data[k]);data.observedAt=new Date(data.observedAt).toISOString();rows=validateObservations([...rows,{...data,id:crypto.randomUUID(),currency:'EUR'}]);save();render();e.target.reset();setDate();message('Η παρατήρηση προστέθηκε.');}catch(err){message(err.message,true);}$('#message').scrollIntoView({behavior:'smooth',block:'center'});};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>3000000)throw Error('Μέγιστο μέγεθος 3 MB.');const data=JSON.parse(await file.text());if(data.demo)throw Error('Τα εξαγόμενα δείγματα δεν εισάγονται ως πραγματικά δεδομένα.');const incoming=validateObservations(Array.isArray(data)?data:data.observations);rows=validateObservations([...(!demo?rows:[]).filter(r=>!incoming.some(x=>x.id===r.id)),...incoming]);demo=false;save();render();message(`Εισήχθησαν ${incoming.length} παρατηρήσεις.`);}catch(err){message(err.message,true);}e.target.value='';};
$('#export').onclick=()=>{const data={schemaVersion:1,demo,exportedAt:new Date().toISOString(),observations:rows,settings:prefs};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='book-scanner'+(demo?'-SYNTHETIC':'')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
let realRows=[];
$('#demo').onclick=()=>{if(!demo)realRows=rows;rows=demoData();demo=true;$('#query').value='';render();message('Το συνθετικό δείγμα χρησιμοποιεί τα τρέχοντα φίλτρα σου.');$('#results').scrollIntoView({behavior:'smooth',block:'center'});};
$('#clear').onclick=()=>{if(demo){rows=realRows;demo=false;render();message('Το δείγμα έκλεισε. Επαναφέρθηκαν τα πραγματικά δεδομένα.');return;}if(!confirm('Να διαγραφούν όλες οι αποθηκευμένες παρατηρήσεις;'))return;rows=[];save();render();};
for(const source of sourceStatus()){const tile=node('div',undefined,'source-tile');tile.append(node('strong',source.name),node('p',source.note));if(source.host){const a=node('a','Αναζήτηση στο site ↗');a.href='https://'+source.host;a.target='_blank';a.rel='noopener noreferrer';tile.append(a);}$('#source-status').append(tile);}
$('#refresh').onclick=async()=>{const button=$('#refresh');button.disabled=true;try{if(demo)throw Error('Κλείσε πρώτα το συνθετικό δείγμα.');prefs=readSettings();const data=await scanRemote($('#backend').value,$('#token').value,$('#query').value,prefs.sources);rows=validateObservations([...rows.filter(r=>!(r.provenance&&prefs.sources.includes(r.source))&&!data.observations.some(x=>x.id===r.id)),...data.observations]);save();render();$('#remote-status').textContent=(data.statuses||[]).map(s=>s.name+': '+s.note).join(' · ')||'Δεν υπάρχουν συνδεδεμένα feeds.';}catch(err){$('#remote-status').textContent=err.message;}finally{button.disabled=false;}};
$('#alerts').onclick=async()=>{try{const u=new URL($('#backend').value);if(u.protocol!=='https:')throw Error('Απαιτείται HTTPS.');u.pathname=u.pathname.replace(/\/$/,'')+'/alerts';u.search='';u.hash='';const r=await fetch(u,{headers:{Authorization:'Bearer '+$('#token').value},signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw Error('Οι ειδοποιήσεις δεν είναι διαθέσιμες: '+r.status);$('#alert-results').textContent=JSON.stringify(await r.json(),null,2);}catch(err){$('#alert-results').textContent=err.message;}};
render();

