import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeOpenLibrary,lookupOpenLibrary} from '../metadata.js';

const payload={docs:[{title:'Animal Farm',isbn:['0141036133','9780141036137'],author_name:['George Orwell'],editions:{docs:[{isbn:['9780141036137'],publisher:['Penguin Books']},{isbn:['9780451526342'],publisher:['Signet Classics']}]}}]};
test('Open Library normalization maps publisher only from the exact edition',()=>{const r=normalizeOpenLibrary(payload,'0141036133');assert.equal(r.isbn,'9780141036137');assert.equal(r.title,'Animal Farm');assert.equal(r.author,'George Orwell');assert.equal(r.publisher,'Penguin Books');assert.equal(normalizeOpenLibrary(payload,'9789601620718'),null);assert.equal(normalizeOpenLibrary(payload,'bad'),null);});
test('lookup uses the documented Search API and caches successful response',async()=>{const memory=new Map(),storage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)};let calls=0;const fetcher=async(url,opts)=>{calls++;assert.equal(url.origin,'https://openlibrary.org');assert.equal(url.pathname,'/search.json');assert.equal(url.searchParams.get('isbn'),'9780141036137');assert.match(url.searchParams.get('fields'),/editions/);assert.equal(opts.headers.Accept,'application/json');return new Response(JSON.stringify(payload));};const first=await lookupOpenLibrary('0141036133',{fetcher,storage,now:Date.parse('2026-09-23T08:00:00Z')});const second=await lookupOpenLibrary('9780141036137',{fetcher,storage,now:Date.parse('2026-09-24T08:00:00Z')});assert.equal(first.cached,false);assert.equal(second.cached,true);assert.equal(calls,1);});
test('lookup fails closed for invalid, missing and HTTP error data',async()=>{await assert.rejects(()=>lookupOpenLibrary('bad',{storage:null}),/έγκυρο ISBN/);await assert.rejects(()=>lookupOpenLibrary('9780141036137',{storage:null,fetcher:async()=>new Response('{}')}),/Δεν βρέθηκε/);await assert.rejects(()=>lookupOpenLibrary('9780141036137',{storage:null,fetcher:async()=>new Response('',{status:429})}),/429/);});

